abstract class InitialData {
  static const data = [
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body':
          'Съеш этих французких булочек Съеш этих французких булочек Съеш этих французких булочек Съеш этих французких булочек Съеш этих французких булочек',
      'emojis': [],
    },
    {
      'id': 1,
      'name': 'VimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
    {
      'id': 1,
      'name': 'TimurKarev',
      'address': '@timurkarev',
      'body': 'Съеш этих французких булочек',
      'emojis': [
        '\u{FE0F}',
        '\u{1F44D}',
        '\u{1F525}',
        '\u{1F970}',
        '\u{1F622}',
      ],
    },
  ];
}
